### ISSUE TITLE
DeployStudioAdmin broken

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/jaharmi-recipes#19]
I think @bochoven broke the DeployStudioAdmin package with e33e5f8579a19ac8a31e69dcfcf0e78108961188  :). The following recipe step needs to have the pkginfo variable but it no longer exists due to `MunkiInstallsItemsCreator` being removed.

**Comment by bochoven** [comment]
Sorry about breaking this. QA here is subpar. :-D

**Comment by jessepeterson** [comment]
No worries. Thanks for the PR! Didn't have a moment to submit myself. Cheers! 👍
