### ISSUE TITLE
Error with Java7JDK munki recipe

### ISSUE THREAD

**Issue by grahampugh** [autopkg/jaharmi-recipes#3]
Hi,

Forgive me if this is related to the previous issue. I get the following error when attempting to run the recipe.  

$ autopkg run OracleJava7JDK.munki
Processing OracleJava7JDK.munki...
creating pkginfo for /Users/ME/Library/AutoPkg/Cache/com.github.jaharmi.munki.OracleJava7JDK/downloads/jdk-7u71-macosx-x64.dmg failed: hdiutil error hdiutil: imageinfo failed - image not recognized
 with image /Users/ME/Library/AutoPkg/Cache/com.github.jaharmi.munki.OracleJava7JDK/downloads/jdk-7u71-macosx-x64.dmg.
hdiutil error hdiutil: imageinfo failed - image not recognized
 with image /Users/ME/Library/AutoPkg/Cache/com.github.jaharmi.munki.OracleJava7JDK/downloads/jdk-7u71-macosx-x64.dmg.
ERROR: Error: "hdiutil: attach failed - image not recognized" while mounting jdk-7u71-macosx-x64.dmg.
Could not mount /Users/ME/Library/AutoPkg/Cache/com.github.jaharmi.munki.OracleJava7JDK/downloads/jdk-7u71-macosx-x64.dmg!

Failed.

**Comment by MichalMMac** [comment]
Same problem here. DMG is empty.
This download recipe seems to work -> https://github.com/autopkg/hansen-m-recipes/blob/master/Oracle/OracleJava7JDK.download.recipe
