### ISSUE TITLE
BoinxTV error

### ISSUE THREAD

**Issue by aanklewicz** [autopkg/jaharmi-recipes#4]
Hey, I'm getting an error when running AutoPKGr, getting this error.

Error in local.munki.BoinxTV: Processor: URLDownloader: Error: Couldn't download https://cdn.boinx.com/software/boinxtv/Boinx_BoinxTV_1.9.12-17142.app.zip (HTTP Error 403: Forbidden)	Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1459, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in local.munki.BoinxTV: Processor: URLDownloader: Error: Couldn't download https://cdn.boinx.com/software/boinxtv/Boinx_BoinxTV_1.9.12-17142.app.zip (HTTP Error 403: Forbidden)

**Comment by Jaharmi** [comment]
This should be fixed as of b6e8b7f62df48e73f1035d92141f5e586b15c532. Thanks to @timsutton. In trying to solve this, I tried merging selections from his Boinx iStopMotion recipe (autopkg/timsutton-recipes). That worked.
