### ISSUE TITLE
Floating ']' on line 57 I believe is a Typo and should not be there.

### ISSUE THREAD

**Issue by revpjbbq** [autopkg/jaharmi-recipes#46]
https://github.com/autopkg/jaharmi-recipes/blob/c99024fd629436801bbee8ab53a931d115bd8b17/AndrewGallant/ripgrep.pkg.recipe#L57

I believe the ']' on line 57 is a Typo and removing this extraneous character resolves all errors in autopkg in using it.

**Comment by homebysix** [comment]
(throws paper airplane at @arubdesu)

**Comment by arubdesu** [comment]
gadddamnit
