### ISSUE TITLE
Rocket Download URL is Stale

### ISSUE THREAD

**Issue by bryanheinz** [autopkg/jaharmi-recipes#52]
The [download URL](https://github.com/autopkg/jaharmi-recipes/blob/803b897b64a655d7686acb8087f24bbb5a14b928/MatthewPalmer/Rocket.download.recipe#L14) for Rocket is pointing to an old version (v1.5.1) and I don't think will point to the latest versions anymore.

The [website](https://matthewpalmer.net/rocket/) has a new download link (https://macrelease.matthewpalmer.net/Rocket.dmg) which points to the latest version (v1.8.2).

In the download recipe I was able to swap the old URL with the new, and the recipe appears to still be working. I'll submit a pull request with the new URL in a minute following posting this Issue.

**Comment by Jaharmi** [comment]
Merged PR, thanks.
