### ISSUE TITLE
Manuscripts - download error

### ISSUE THREAD

**Issue by TomBoehm** [autopkg/jaharmi-recipes#63]
curl https://updates.manuscriptsapp.com/apps/manuscripts/beta/appcast.xml
curl: (60) SSL certificate problem: unable to get local issuer certificate

The site uses a self-signed certificate

**Comment by Jaharmi** [comment]
@TomBoehm thanks, I'll look into this more.

**Comment by Jaharmi** [comment]
As of this writing, the host cannot be resolved, so there’s more to investigate.

**Comment by Jaharmi** [comment]
I get an error when trying to use the "Check for Updates" command in Manuscripts' app menu.

![Screen Shot 2022-12-20 at 5 47 45 PM](https://user-images.githubusercontent.com/214152/208784115-1b8b7394-15ee-47ec-8774-9bd0a4791641.png)

**Comment by Jaharmi** [comment]
I have not been able to resolve this and don't have a response to my question to the developer.

**Comment by Jaharmi** [comment]
@TomBoehm I haven’t seen any reply about this from the developer.

I’d be happy to accept a PR to remove the related recipes and tag it for Hacktoberfest, if that’s of interest to you.
