### ISSUE TITLE
Hyperdither recipes return a 404

### ISSUE THREAD

**Issue by flammable** [autopkg/jaharmi-recipes#68]
It looks like the Dropbox URL has been replaced with a Mac App Store link. :/

https://www.tinrocket.com/content/hyperdither/

**Comment by Jaharmi** [comment]
Well, that is unfortunate.

**Comment by Jaharmi** [comment]
I sent a message to the developer/vendor, to clarify the download situation.

**Comment by flammable** [comment]
Thanks @Jaharmi!

**Comment by Jaharmi** [comment]
No problem @flammable. Assuming I notice any reply from Tinrocket, I will update this issue. :)

**Comment by Jaharmi** [comment]
@flammable I haven’t seen any reply about this from the developer. The product Web site still indicates _only_ a Mac App Store link.

I’d be happy to accept a PR to remove the HyperDither recipes and tag it for Hacktoberfest, if that’s of interest to you.
