### ISSUE TITLE
Olympus.A-GPSUtility.install.recipe is potentially an invalid file

### ISSUE THREAD

**Issue by jby** [autopkg/jaharmi-recipes#74]
When testing the 2.8.1 RC it complains about this recipe:
WARNING: /Users/jonasb/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes/Olympus/Olympus.A-GPSUtility.install.recipe is potentially an invalid file, not adding it to the recipe map! Please file a GitHub Issue for this repo.
More info here: https://macadmins.slack.com/archives/C056155B4/p1691608955567799

**Comment by Jaharmi** [comment]
Working on this now, clearly very delayed from original request. :|

**Comment by Jaharmi** [comment]
Fixed by #75

Thank you for submitting this @jby
