### ISSUE TITLE
new SPARKLE_FEED_URL for GeekTool

### ISSUE THREAD

**Issue by jpenney** [autopkg/jaharmi-recipes#8]
GeekTool 3.1.9 has been out since march, but the current feed still lists 3.1.8.  After some digging I figured out the new feed is `https://updates.devmate.com/org.tynsoe.GeekTool.xml`

**Comment by macmule** [comment]
@jpenney thanks for logging the issue.. was just about to do the same!

**Comment by Jaharmi** [comment]
@jpenney @macmule Sorry, I missed this issue. There's now a PR on it, which helps.

**Comment by Jaharmi** [comment]
#13 resolves issue with Sparkle feed.
